import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    // Generated by @opennextjs/cloudflare during the production e2e build.
    ".open-next/**",
    "out/**",
    "build/**",
    // The API is a separate repository with its own generated sources and toolchain.
    "backend/**",
    "next-env.d.ts",
  ]),
]);

export default eslintConfig;
