import type { Metadata } from "next";

import { routing } from "@/i18n/routing";

/**
 * SEO plumbing (docs/SPEC.md §9).
 *
 * The governing rule: **public content is indexable, anything personal is `noindex`.**
 * Every page picks a side explicitly — there is no safe default when a learner's profile
 * and a dictionary entry live in the same app.
 */

export const SITE_URL = (
    process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000"
).replace(/\/$/, "");

export type Locale = (typeof routing.locales)[number];

/** `/en/english/a1` — locale-prefixed absolute path. */
export const localePath = (locale: string, path = "") => {
    const clean = path.replace(/^\//, "");
    return clean ? `/${locale}/${clean}` : `/${locale}`;
};

export const absoluteUrl = (path: string) => `${SITE_URL}${path}`;

/**
 * Canonical + hreflang for one logical page.
 *
 * Without these the `en` and `th` renderings of the same word compete with each other,
 * and Google picks a winner we did not choose.
 */
export const alternatesFor = (locale: string, path = ""): Metadata["alternates"] => {
    const languages: Record<string, string> = {};

    for (const other of routing.locales) {
        languages[other] = absoluteUrl(localePath(other, path));
    }

    languages["x-default"] = absoluteUrl(
        localePath(routing.defaultLocale, path),
    );

    return {
        canonical: absoluteUrl(localePath(locale, path)),
        languages,
    };
};

/**
 * The social preview card, generated by `scripts/generate-brand-assets.mjs`.
 *
 * `twitter.card = "summary_large_image"` is a promise that an image exists; without one,
 * X, Facebook, Discord and — for this audience, the one that matters — LINE render a
 * blank card for every URL on the site. The card carries no text, deliberately: every
 * platform draws `og:title` and `og:description` as live text beside it, and baking Thai
 * into the bitmap would mean shipping a Thai font to the image pipeline.
 */
const OG_IMAGE = {
    url: absoluteUrl("/og.png"),
    width: 1200,
    height: 630,
    alt: "Vocab Learning — Oxford 3000",
};

/** Metadata for a public, indexable page. */
export const publicMetadata = ({
    locale,
    path = "",
    title,
    description,
    index = true,
}: {
    locale: string;
    path?: string;
    title: string;
    description: string;
    /**
     * Escape hatch for pages that are public but must stay out of the index — a word
     * entry that fails the substance floor, for instance. `follow` stays on, so the
     * crawler still walks onward to the pages that do qualify.
     */
    index?: boolean;
}): Metadata => ({
    title,
    description,
    alternates: alternatesFor(locale, path),
    robots: { index, follow: true },
    openGraph: {
        type: "website",
        title,
        description,
        url: absoluteUrl(localePath(locale, path)),
        locale,
        siteName: "Vocab Learning",
        images: [OG_IMAGE],
    },
    twitter: {
        card: "summary_large_image",
        title,
        description,
        images: [OG_IMAGE.url],
    },
});

/**
 * Metadata for anything personal or transactional. `noindex, nofollow` and no canonical —
 * a learner's mistakes bank must never be a search result.
 */
/**
 * Deliberately no canonical, and `e2e/seo.spec.ts` enforces it.
 *
 * A canonical is a request to index *this* URL instead of another one; on a page that is
 * already `noindex, nofollow` it says nothing useful and quietly re-opens the question of
 * whether the page belongs in an index at all. The extra `locale`/`path` arguments are
 * accepted so callers can pass their identity without the signature changing again later,
 * but they intentionally do not produce one.
 */
export const privateMetadata = (
    title: string,
    _locale?: string,
    _path = "",
): Metadata => ({
    title,
    robots: {
        index: false,
        follow: false,
        nocache: true,
        googleBot: { index: false, follow: false },
    },
});

/**
 * The one canonical node for the word list itself.
 *
 * Every word page declares the sense it documents as a member of this set. They used to
 * do that with the bare string `"Oxford 3000"` — a name, not an entity, so ~5,600 pages
 * pointed at something that existed nowhere. The A–Z index publishes the matching
 * `DefinedTermSet` under this `@id`; everything else references it.
 *
 * Locale-free on purpose: the Oxford 3000 is one list, whichever language explains it.
 */
export const OXFORD_3000_TERMSET_ID = absoluteUrl("/#oxford-3000");

/** The publisher node. Referenced by `@id` rather than repeated per page. */
export const ORGANISATION_ID = absoluteUrl("/#organisation");

/** The site node, for entity-graph consistency across the two locales. */
export const WEBSITE_ID = absoluteUrl("/#website");

/** JSON-LD helper — returns the props for a `<script type="application/ld+json">`. */
export const jsonLd = (data: Record<string, unknown>) => ({
    type: "application/ld+json" as const,
    dangerouslySetInnerHTML: { __html: JSON.stringify(data) },
});
